apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-provisioner
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hostpath-provisioner
  template:
    metadata:
      labels:
        app: hostpath-provisioner
    spec:
      serviceAccountName: hostpath-provisioner
      containers:
        - name: hostpath-provisioner
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_HOST_PATH
              value: {{ .Values.nodeHostPath }}
          volumeMounts:
            - mountPath: /mnt/hostpath
              name: hostpath
      volumes:
        - name: hostpath
          hostPath:
            path: {{ .Values.nodeHostPath }}
