---
replicaCount: 1
image:
  repository: ghcr.io/rhythmbhiwani/hostpath-provisioner
  tag: v1.0.4
  pullPolicy: IfNotPresent
provisionerName: hostpath
nodeHostPath: /mnt/hostpath
rbac:
  create: true
storageClass:
  create: true
  name: hostpath
  reclaimPolicy: Delete
  volumeBindingMode: Immediate